In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df_19=pd.read_csv(r"C:\Users\joshd\Downloads\2019-UK-Notional-results.csv")
df_24=pd.read_csv(r"C:\Users\joshd\Downloads\HoC-GE2024-results-by-candidate.csv",
               usecols=['ONSID','Constituencyname','Partyname','Partyabbreviation','Share','Countryname'])

In [9]:
df_19=df_19.loc[(df_19.Countrygeographiccode!='9N92000002') & (df_19.Mainpartyabbreviation=='Lab')]
df_24=df_24.loc[(df_24.Countryname!='Northern Ireland') & (df_24.Partyabbreviation=='Lab')]

In [31]:
a=df_19.merge(df_24,how='left',left_on='Constituencygeographiccode',right_on='ONSID')

In [32]:
a.drop(['Countryname_x','Countrygeographiccode','Constituencydesignation','Constituencyname_x','Constituencygeographiccode','Mainpartyname','Mainpartyabbreviation','Partyname','Partyabbreviation'],axis=1,inplace=True)
a.head()

,Candidatevoteshare,ONSID,Constituencyname_y,Countryname_y,Share
0,0.529208,W07000081,Aberafan Maesteg,Wales,0.498895
1,0.119796,S14000060,Aberdeen North,Scotland,0.303433
2,0.041708,S14000062,Aberdeenshire North and Moray East,Scotland,0.101498
3,0.087673,S14000061,Aberdeen South,Scotland,0.247168
4,0.331111,S14000063,Airdrie and Shotts,Scotland,0.514673

In [35]:
a['diff']=a.Share-a.Candidatevoteshare
a['diff']*=100
a.head()

,Candidatevoteshare,ONSID,Constituencyname_y,Countryname_y,Share,diff
0,0.529208,W07000081,Aberafan Maesteg,Wales,0.498895,-3.031280
1,0.119796,S14000060,Aberdeen North,Scotland,0.303433,18.363728
2,0.041708,S14000062,Aberdeenshire North and Moray East,Scotland,0.101498,5.979048
3,0.087673,S14000061,Aberdeen South,Scotland,0.247168,15.949491
4,0.331111,S14000063,Airdrie and Shotts,Scotland,0.514673,18.356246

In [36]:
a.sort_values('diff')

,Candidatevoteshare,ONSID,Constituencyname_y,Countryname_y,Share,diff
72,0.762206,E14001120,Bradford West,England,0.316173,-44.603300
47,0.829999,E14001096,Birmingham Ladywood,England,0.425326,-40.467285
37,0.735120,E14001086,Bethnal Green and Stepney,England,0.340772,-39.434840
53,0.659824,E14001102,Blackburn,England,0.267082,-39.274160
163,0.590898,E14001196,Dewsbury and Batley,England,0.228710,-36.218820
...,...,...,...,...,...,...
30,0.187941,S14000068,Bathgate and Linlithgow,Scotland,0.470082,28.214121
7,0.145035,S14000064,Alloa and Grangemouth,Scotland,0.437829,29.279418
116,0.141466,S14000109,Central Ayrshire,Scotland,0.436780,29.531355
212,0.120707,S14000083,Falkirk,Scotland,0.430334,30.962700
190,0.123833,S14000021,East Renfrewshire,Scotland,0.436717,31.288442

In [37]:
a.to_csv(r"C:\Users\joshd\Downloads\Labour-Vote-Change.csv")